### ISSUE TITLE
Open Stable Diffusion on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [Jokimax/OpenStableDiffusion#13]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have Open Stable Diffusion listed in the repo. Please review the listing at https://www.openapk.net/open-stable-diffusion/com.openstablediffusion//

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by Jokimax** [comment]
Seems great. I have no problem with this.

**Comment by mobilenetworkltd** [comment]
Hello,

thank you for the fast response. It is important to be as accurate as possible since I want my users to be aware of the developers info and to be able to send you a donation also.  Please feel free to message me if you notice something else I can improve.

**Comment by Jokimax** [comment]
Yeah. Thanks for including me in your store. I don't have a donation link currently so there is no need to provide one in the store.
