### ISSUE TITLE
Download of result fails - permission denied

### ISSUE THREAD

**Issue by sandoxy** [Jokimax/OpenStableDiffusion#3]
Trying to download the result fails every time. Permission in the phone is granted.![signal-2023-10-06-21-42-15-670.jpg](https://github.com/Jokimax/OpenStableDiffusion/assets/38521726/a8b9df87-1fdf-4dd8-9c9a-42e48e7f81c7)

**Comment by Jokimax** [comment]
Thanks for the bug report.
Are you using external storage(sd card and such)?
Thanks in advance.

**Comment by sandoxy** [comment]
No, there is just an infernal storage in this phone.

**Comment by Jokimax** [comment]
Interesting. 
What phone are using?
And are you using any custom roms(GrapheneOS, LineageOS, etc...)?

**Comment by sandoxy** [comment]
It's a Xiaomi Redmi Note 7 without a custom rom. I reinstalled the app and restarted the phone, but the problem persists.
