### ISSUE TITLE
Line break for long prompts

### ISSUE THREAD

**Issue by sandoxy** [Jokimax/OpenStableDiffusion#4]
When I enter long prompts I cannot see the whole prompt after the line gets full and them I have to move the courser in order to see what I entered at the beginning. 

Maybe a line break, when the single line gets full, could help.

**Comment by Jokimax** [comment]
I will consider it. But I feel like it looks better, if the input box keeps a constant size

**Comment by sandoxy** [comment]
I agree, constant size looks better. Maybe static two lines could be a compromise between usability and design. But maybe I'm wrong.

**Comment by Jokimax** [comment]
After some though I decided to keep as is. I feel like a multi-line input feels too look ugly. Thanks for the input anyway.
